# Generated by Django 3.2.6 on 2021-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(help_text='Member ID', primary_key=True, serialize=False),
        ),
    ]
