# Generated by Django 3.2.6 on 2021-09-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='phoneNum',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='info',
        ),
    ]
