# Generated by Django 3.2.6 on 2021-09-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20210926_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visited',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
