# Generated by Django 3.2.6 on 2021-09-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20210926_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
        migrations.AlterField(
            model_name='visited',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_id', to='member.member'),
        ),
    ]
