# Generated by Django 3.2.6 on 2021-10-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20210926_0707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visited',
        ),
    ]
